@startuml

skinparam classAttributeIconSize 0


class Usuario {
    -id: int
    -nome: string
    -email: string
    -senha: string
    +acessarSistema(): void
}

class Cliente {
    +visualizarListagemLivros(): void
    +pesquisarLivrosPorTitulo(titulo: string): List<Livro>
    +solicitarEmprestimo(livro: Livro): void
    +visualizarDataPrevistaEntrega(): Date
    +reservarLivroOcupado(livro: Livro): void
    +renovarEmprestimo(emprestimo: Emprestimo): void
}

class Bibliotecario {
    +visualizarSolicitacoes(): List<SolicitacaoEmprestimo>
    +aceitarSolicitacao(s: SolicitacaoEmprestimo): void
    +recusarSolicitacao(s: SolicitacaoEmprestimo): void
    +registrarDevolucao(emprestimo: Emprestimo): void
    +editarLivro(livro: Livro): void
    +excluirLivro(livro: Livro): void
    +adicionarLivro(livro: Livro): void
}

class Livro {
    -id: int
    -titulo: string
    -autor: string
    -ano: int
    -disponivel: boolean
}

class Emprestimo {
    -id: int
    -livro: Livro
    -cliente: Cliente
    -dataEmprestimo: Date
    -dataPrevistaEntrega: Date
    -dataDevolucao: Date
    -renovado: boolean
}

class SolicitacaoEmprestimo {
    -id: int
    -livro: Livro
    -cliente: Cliente
    -status: string
    -dataSolicitacao: Date
}

class Reserva {
    -id: int
    -livro: Livro
    -cliente: Cliente
    -dataReserva: Date
}


Usuario <|-- Cliente
Usuario <|-- Bibliotecario


Livro "1" <-- "0..*" Emprestimo
Cliente "1" <-- "0..*" Emprestimo
Livro "1" <-- "0..*" SolicitacaoEmprestimo
Cliente "1" <-- "0..*" SolicitacaoEmprestimo
Livro "1" <-- "0..*" Reserva
Cliente "1" <-- "0..*" Reserva

@enduml
